import { Listing, Order, User } from "@/types";

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    farmerId: "farmer-1",
    farmerName: "Seun Damilola",
    cropName: "Tomatoes",
    quantity: 500,
    unit: "kg",
    price: 2800,
    location: "Calabar, Nigeria",
    status: "active",
    createdAt: new Date("2024-12-01"),
  },
  {
    id: "listing-2",
    farmerId: "farmer-1",
    farmerName: "Grace Richard",
    cropName: "Maize",
    quantity: 1000,
    unit: "kg",
    price: 3000,
    location: "Lagos, Nigeria",
    status: "active",
    createdAt: new Date("2024-12-05"),
  },
  {
    id: "listing-3",
    farmerId: "farmer-2",
    farmerName: "Mary Green",
    cropName: "Rice",
    quantity: 2000,
    unit: "kg",
    price: 5500,
    location: "Ibadan, Nigeria",
    status: "active",
    createdAt: new Date("2024-12-10"),
  },
  {
    id: "listing-4",
    farmerId: "farmer-2",
    farmerName: "Mary Green",
    cropName: "Yam",
    quantity: 800,
    unit: "tubers",
    price: 200,
    location: "Ibadan, Nigeria",
    status: "active",
    createdAt: new Date("2024-12-12"),
  },
  {
    id: "listing-5",
    farmerId: "farmer-3",
    farmerName: "Peter Harvest",
    cropName: "Rice",
    quantity: 1500,
    unit: "kg",
    price: 120,
    location: "Abuja, Nigeria",
    status: "active",
    createdAt: new Date("2024-12-15"),
  },
  {
    id: "listing-6",
    farmerId: "farmer-3",
    farmerName: "Peter Harvest",
    cropName: "Beans",
    quantity: 600,
    unit: "kg",
    price: 180,
    location: "Abuja, Nigeria",
    status: "active",
    createdAt: new Date("2024-12-18"),
  },
];

export const mockOrders: Order[] = [
  {
    id: "order-1",
    listingId: "listing-1",
    buyerId: "buyer-1",
    farmerId: "farmer-1",
    cropName: "Tomatoes",
    quantity: 100,
    unit: "kg",
    totalAmount: 15000,
    status: "pending",
    escrowStatus: "held",
    createdAt: new Date("2024-12-20"),
    buyerName: "Sarah Buyer",
    farmerName: "John Farmer",
  },
  {
    id: "order-2",
    listingId: "listing-2",
    buyerId: "buyer-1",
    farmerId: "farmer-1",
    cropName: "Maize",
    quantity: 200,
    unit: "kg",
    totalAmount: 16000,
    status: "accepted",
    escrowStatus: "held",
    createdAt: new Date("2024-12-18"),
    buyerName: "Sarah Buyer",
    farmerName: "John Farmer",
  },
  {
    id: "order-3",
    listingId: "listing-3",
    buyerId: "buyer-2",
    farmerId: "farmer-2",
    cropName: "Cassava",
    quantity: 500,
    unit: "kg",
    totalAmount: 22500,
    status: "completed",
    escrowStatus: "released",
    createdAt: new Date("2024-12-15"),
    buyerName: "Mike Wholesale",
    farmerName: "Mary Green",
  },
];

export const mockUsers: User[] = [
  {
    id: "farmer-1",
    name: "John Farmer",
    email: "john@farm.com",
    role: "farmer",
    location: "Lagos, Nigeria",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "farmer-2",
    name: "Mary Green",
    email: "mary@farm.com",
    role: "farmer",
    location: "Ibadan, Nigeria",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "farmer-3",
    name: "Peter Harvest",
    email: "peter@farm.com",
    role: "farmer",
    location: "Abuja, Nigeria",
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "buyer-1",
    name: "Sarah Buyer",
    email: "sarah@buy.com",
    role: "buyer",
    location: "Abuja, Nigeria",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "buyer-2",
    name: "Mike Wholesale",
    email: "mike@wholesale.com",
    role: "buyer",
    location: "Lagos, Nigeria",
    createdAt: new Date("2024-04-05"),
  },
];

export const cropImages: Record<string, string> = {
  Tomatoes:
    "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop",
  Maize:
    "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop",
  Cassava:
    "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop",
  Yam: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=400&h=300&fit=crop",
  Rice: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop",
  Beans:
    "https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=400&h=300&fit=crop",
};
